-- Exemple de tweak documentaire — la base principale applique déjà Remux / Full Disc à -999999.
-- Ne duplique pas ces lignes sauf surcharge locale explicite.

-- INSERT INTO quality_profile_custom_formats ...
-- SELECT 'FR-Films-4K', 'Remux', 'all', -999999 ...
