-- Fichier 03 : définitions des custom formats (Radarr + Sonarr)

-- Custom formats

INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('3D', 'Repère tout contenu vidéo **stéréoscopique 3D** (« Bluray3D », **SBS** half/full, tags selon regex `3D`). Souvent **malus dur** puisque peu d’installations domestiques utilisent encore la 3D active/passive.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('AAC', 'Détecte la présence du codec audio **AAC** dans le titre de release (indexeur).
Le bloc de conditions suivant exclut l’activation si le titre announce en parallèle
d’autres formats audio listés (« negate »), afin de ne scorer qu’une piste prédominante
cohérente avec le parsing Servarr/Dictionarry d’origine.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('AV1', 'Codec **AV1** — **proscrit** sur tous les profils FR (score -999999). Incompatible avec une large part du matériel (TV, box, lecteurs) en usage domestique ; seuls HEVC/H.265/x265 sont visés en 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Atmos', 'Détecte Dolby Atmos (titre DDPA / ATMOS) et la convention Atmos BTN / TrueHD.A 5.1–7.1 via la regex projet FR-Regex-Atmos-Bundle.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS-ES', 'Détecte **DTS-ES** (extension surround matricielle) dans la release. Agrège exclusions vers les autres codecs
du pack commun (DTS:X, Dolby, FLAC, AAC, TrueHD…) pour empêcher le cumul aberrant lorsque plusieurs badges
s’entrechoquent dans le même titre indexer.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS-HD HRA', 'Détecte **DTS-HD High Resolution Audio** (« HRA »). Les exclusions mutuelles éviteront de classer plusieurs
bonus audio différents (DTS‑HD MA, DTS:X, Dolby TrueHD, FLAC…) lorsque plusieurs tags légitimes se superposent
dans une release internationale brute.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS-HD MA', 'Détecte **DTS-HD Master Audio** (« lossless core + extension » tel qu’annoncé). Les négations couvrent
DTS:X, Dolby TrueHD/Atmos, FLAC, DTS-HRA + variantes résiduelles (**DTS-HD HRA ES**) pour garantir une seule
note « meilleure » famille audio par ligne quand plusieurs tags audio coexistent.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS-X', 'Détecte **DTS:X** objet dans le titre. Les négations sur DTS‑HD MA, TrueHD sans Atmos équivalent etc.
garantissent qu’une seule « famille » DTS premium prévaut lors du passage des conditions combinées Servarr,
suivant toujours le schéma de conflits hérité de Dictionarry.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS', 'Détecte **DTS** « de base » (non HD) dans la chaîne. Exclut l’activation si des variantes DTS‑HD /
DTS‑X présentes seraient mieux représentées par leurs CF dédiées — liste négative issue du pack
Dictionarry standard.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Dolby Digital +', 'Détecte **Dolby Digital Plus** (**E‑AC‑3**) dans la release. Mutualise exclusions audio
(AAC, FLAC, autres DTS…) pour éviter double compte lorsque le titre annonce plusieurs normes à la fois,
comportement fidèle au template Dictionarry.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Dolby Digital', 'Détecte « Dolby Digital » (AC‑3 léger hors **Dolby Digital+** explicitement différent dans
vos autres CF). Les exclusions couvrent les autres familles DTS/TrueHD/etc. présentes dans ce
bundle pour éviter chevauchement de notation audio.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Dolby Vision (Without Fallback)', '**Dolby Vision sans HDR10 fallback lisible dans le titre** : cas problématiques pour lecteurs anciens où seule la couche DV est taguée hors combinaisons **HDR10 / REMUX Blu-ray**. Utilisée en léger malus (« Without Fallback ») sur profils pensés pour la compatibilité matérielle domestique généraliste lorsque aucune mention HDR de secours ne parait sur la ligne de release brute.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Dolby Vision', 'Repère explicitement les alias **DV / DoVi / Dolby Vision** annoncés dans le titre indexer. Regex exclut volontairement associations **DV+HLG** ou **DV+SDR triviales** (voir motif) pour se concentrer sur les releases réellement positionnées comme Dolby Vision consommable (voir documentation technique DV du fabricant Dolby).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FLAC', 'Détecte la présence du codec **FLAC** (sans perte) annoncée pour la piste audio principale dans le titre.
Les conditions négatives évitent de cumuler avec Dolby Digital(+), DTS, AAC, PCM ou TrueHD lorsque plusieurs
mentions contradictoires apparaissent sur une même ligne d’indexation — comportement éprouvé Dictionarry / TRaSH.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-4KLight', 'Détecte le tag 4KLight (Bluray 4K UHD allégé, qualité préservée avec taille réduite). Format de référence sur C411 — particulièrement les releases QTZ et BONBON. À privilégier fortement sur les profils 4K (cible « cinéma maison » avec stockage raisonnable).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Blockers', 'Détecte les releases problématiques pour la scène FR — groupes bannis (k0RE, Wawacity, YIFY, FGT, GalaxyRG, etc.), encodeurs GPU interdits (NVENC, QSV, AMF) et incohérences techniques majeures (REMUX / BDMV / ISO combinés avec un codec encoder x264/x265/h264/h265). Score très négatif pour exclure totalement de la sélection.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-HDLight', 'Détecte le tag HDLight (Bluray allégé typique scène FR). Petit bonus pour identification d''un format compact courant sur trackers FR — utile en 720p / 1080p / Any, neutre voire à pénaliser en 4K (HDLight n''existe quasiment pas en 2160p).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Hybrid', 'Détecte le tag HYBRID (Bluray hybride). Référence premium UHD. Bonus modéré si le titre mentionne explicitement cet assemblage.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-MULTI-VF2', 'Détecte les releases annonçant à la fois MULTI ET un tag VF2, VFQ ou VOQ (inclut la variante québécoise « VOQ » visible chez QTZ et équivalents). Représente le pack audio multi-pistes avec variante Québec / seconde VF — cible de meilleure compatibilité linguistique (le plus haut score langue du système).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-MULTI-VFF', 'Détecte les releases annonçant à la fois MULTI ET un tag FR hors VFQ/VF2/VOQ (VFF, TRUEFRENCH, VFI, VOF, VFB, VF générique). Le tag VOQ relève de FR-MULTI-VF2. Représente le pack audio FR multi-langues le plus courant sur la scène FR (préféré sur la VF mono-piste).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Repack-2', 'PROPER2 / REPACK2 ou chaîne REAL…PROPER. Pourquoi : seconde passe de correction — bonus supérieur à FR-Repack.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Repack-3', 'PROPER3 / REPACK3. Pourquoi : correction la plus aboutie annoncée — bonus maximal repack.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Repack', 'PROPER / REPACK / RERIP / REAL simple (sans 2/3). Pourquoi : correction qualité dans le titre ; media en doNotPrefer — le score CF choisit la release. Voir FR-Repack-2/3 pour itérations suivantes.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Streamer-Premium', 'Détecte les sources WEB premium dans le titre : Netflix (NF), Prime Video (AMZN), Disney+ (DSNP), Apple TV+ (ATVP), HBO Max / Max, Paramount+ (PMTP). Pourquoi : master studio récent souvent meilleur que WEB générique ; bonus modéré sur profils FR-*.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Streamer-Standard', 'Détecte les sources WEB secondaires visibles sur trackers FR : Sky NOW, Crunchyroll, iTunes/IT (WEB). Pourquoi : pertinent pour animé (CR) et achats Apple ; Hulu/Peacock exclus (peu de catalogue FR).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-AMEN', 'Équipe AMEN — WEB 2160p compact (DV/HDR10+). Pourquoi : encodeur reconnu sur trackers francophones ; bonus de priorité (scores ops/06).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-BONBON', 'Équipe BONBON — 2160p 4KLight / WEBRip compact (~2,5–5 Go). Pourquoi : référence taille/qualité en UHD allégé ; fort bonus sur profils 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-BOUC', 'Équipe BOUC — WEB 2160p premium (DV/HDR10+, MULTI). Pourquoi : catalogue haut de gamme ; parfois EXCLU C411 — score modéré.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-ENIGMA', 'Équipe ENIGMA — WEB 1080p/2160p (H264/H265, EAC3, HDR10 en 4K). Pourquoi : fort catalogue VFQ et blockbusters MULTI sur la scène FR.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-FW', 'Équipe Forward (FW / FORWARD) — WEB 2160p catalogue (~9–20 Go). Pourquoi : volume et régularité ; bonus intermédiaire dans les profils FR-*.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-HYPERION', 'Équipe HYPERION — quasi exclusivement Remux UHD/1080p (TrueHD Atmos, DV). Pourquoi : détectée pour transparence ; Remux à -999999 sur nos profils → jamais retenue.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-OZEF', 'Équipe OZEF — Remux Blu-ray/UHD (TrueHD, DTS-HD MA). Pourquoi : idem HYPERION — Remux proscrit (-999999) sur profils stricts FR-*.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-PopHD', 'Équipe PopHD — 1080p BluRay/HDLight x264 (~2–4 Go), MULTI VFF/VF2. Pourquoi : bon compromis 1080p compact ; bonus modéré sur profils 720p/1080p.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-QTZ', 'Équipe QTZ — référence 4KLight Bluray (qualité / taille). Pourquoi : équipe de référence C411 en 4K allégé ; parmi les plus hauts scores team.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-SUPPLY', 'Équipe SUPPLY — WEB 2160p premium (H265, DV/HDR10+, Atmos, ~10–25 Go). Pourquoi : qualité image et audio élevée ; bonus fort sur profils 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-Slay3R', 'Équipe Slay3R — WEB 2160p volume / exclus. Pourquoi : sorties fréquentes et complètes (tags DV/HDR) ; bonus élevé 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-TFA', 'Équipe TFA — WEB 2160p MULTI (VFF/VF2), HDR/DV (~10–18 Go). Pourquoi : catalogue séries/films régulier ; bonus intermédiaire-haut.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-THESYNDiCATE', 'Équipe THESYNDiCATE — WEB 2160p H265/x265 (~8–22 Go). Pourquoi : bon rapport qualité/taille ; les sorties AV1 restent exclues (-999999).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-TOXIC', 'Équipe TOXIC — 1080p HDLight compact (BluRay/WEBRip, x264). Pourquoi : souvent cumul FR-HDLight ; utile 720p/1080p, peu pertinent en 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-TyHD', 'Équipe TyHD — WEB/WEBRip 2160p HEVC compact. Pourquoi : alternative légère au 4K premium ; bonus modéré sur profils 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Tier-01', 'Palier 01 — encodeurs longue traîne « haute » (BOUBA, NEOSTARK, …). Pourquoi : bonus sous les équipes FR-Team-* documentées ; voir regex FR-Tier-01.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Tier-02', 'Palier 02 — encodeurs longue traîne « basse » (TLC, DFE, KPORAL, …). Pourquoi : petit bonus de reconnaissance ; toujours sous FR-Team-* et FR-Tier-01.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-VF2', 'Détecte la présence d''un tag VF2, VFQ ou VOQ dans le titre, sans exiger MULTI. Couvre les doublages québécois (VFQ, VOQ ex. releases QTZ) ou « second doublage français » (VF2). À combiner avec les scores de profil pour ajuster la politique VFQ/VOQ selon la cible (France vs Québec).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-VFF', 'Détecte la présence d''un tag FR hors VFQ/VF2 (VFF, TRUEFRENCH, VFI, VOF, VFB, VF générique) dans le titre, sans exiger MULTI. Sert à scorer les doublages français « purs » (mono-piste FR) sur les trackers type C411 (La Cale, Gemini).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-VOSTFR', 'Détecte les variantes VOSTFR / VOST-FR / SUBFRENCH / FANSUB / FASTSUB (version originale avec sous-titres français annoncés). Repli de langue accepté lorsqu''aucun doublage MULTI / VFF / VF2 n''est disponible sur l''indexeur.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Full Disc', 'Indique une **image disque Blu-ray intacte ou ISO / structure complète** dans le titre (regex `Full Disc`). Mutualise exclusions **WEB-DL / WEBRip**, **Remux** et codecs **x264/x265 annoncés** pour distinguer véritable transport disque fichier-image vs encodes classiques indexer.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('HDR', 'Repère une mention **HDR** « fourre-tout » dans le titre quand elle n’est **pas** mieux précisée comme **HDR10**, **HDR10+**, pas plus signalée comme **SDR**, **PQ** isolé ou **HLG** (voir exclusions). Réduit le risque de double noter HDR plusieurs fois alors que Dolby Vision peut coexister sur d’autres CF suivant profil.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('HDR10+', 'Détecte **HDR10+ / HDR10 PLUS** (« dynamic HDR metadata », souvent accolé après **HDR10** dans les noms de fichiers trackers). Négations **SDR / PQ standalone / HLG** pour éviter faux positifs quand différentes couches HDR coexistent verbalement dans la release.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('HDR10', 'Détecte **HDR10** « strict » lorsque le titre n’emploie pas immédiatement les suffixes **+**, **PLUS** réservés à HDR10+ (voir regex **HDR10+** projet). Complète **Dolby Vision** et **HDR** générique pour granularité scoring HDR sur stack FR.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('IMAX Enhanced', 'Détecte la mention **IMAX Enhanced** dans le titre lorsque catalogue ou indexeur précise cette **livraison « IMAX à domicile »** associée (**Disney+**, collaborations **Sony Bravia CORE** / **BC**, autres déploiements studio selon nomenclatures locales). Séparée du bonus **IMAX** « générique » : évite **d’additionner deux fois** le même film quand une édition ne porte que l’aspect **Enhanced** alors qu’une autre ne cite que **IMAX** sans qualifier.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('IMAX', 'Détecte une déclinaison **IMAX classique** (ciné expansé / mastering IMAX hors cas « Enhanced streaming » géré séparément). Le CF exclut **IMAX Enhanced** résolu par regex dédiée pour éviter le double-score.
', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Opus', 'Détecte la piste Opus dans le titre. La négation « groupe OPUS » a été retirée : en cas de faux positif sur un release group -OPUS, ajuster le score ou réintroduire un motif dédié.
', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('PCM', 'Détecte le **PCM / LPCM non compressé** annoncé dans le titre audio. Mutualise avec des
négations sur AAC, Dolby, DTS familles pour éviter un double-score audio lorsque plusieurs
mentionnent différentes pistes contradictoirement sur une même ligne d’indexation.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Remux', 'Marque une release **REMUX** (flux copiés sans ré-encodage depuis Blu-ray/UHD). Pourquoi : fichiers très volumineux, peu adaptés au stockage domestique ; nos profils FR-* appliquent **-999999** partout (y compris FR-Films-Any) — seuls les **encodes** (WEB, 4KLight, x265…) sont visés.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Season Pack', 'Identifie un **Season Pack Sonarr** (saison complète ramenée dans **un seul** flux de téléchargement). Petit bonus utile lorsque vos indexeurs mettent en avant **l’ensemble d’une saison** plutôt qu’un épisode isolé tout en gardant les règles **qualités natives Sonarr** inchangées dans l’instance.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Theatrical', 'Édition **Theatrical** détectée sur le titre. La prise en charge globale de la mention **« édition spéciale »** a été retirée volontairement — seuls les marqueurs **IMAX** restent gérés par les **formats personnalisés** dédiés pour éviter un double classement.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('TrueHD', 'Détecte **TrueHD Dolby** (« Dolby TrueHD », parfois lié implicitement ou non à une piste Atmos séparée).
Liste négative identique aux bundles Dictionarry pour isoler DTS:X / DTS‑HD MA / FLAC lorsqu’ils seraient mieux représentés
comme signal principal dans le titre.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('UHD Bluray', 'Indique un downscale 1080p provenant d''une source UHD annoncée dans le titre, avec HDR (Basic HDR Formats). La condition par groupe (liste restrictive) a été retirée : tout groupe peut déclencher le bonus si le titre reste cohérent.
', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Upscaled', 'Malus **fort / blocage** (-999999) pour releases **explicitement upscalées** : marqueurs « Upscale », regrade colorimétrique, tags **IA** / **AIUS** (regex `Upscaled` — seul CF de blocage upscale sur tous les profils FR).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('VP9', 'Repère mentions **VP9** (flux issus de pipelines type Google/streaming léger ou certains épisodes anime WEB). Malus léger (« -200 ») car on privilégie en général **HEVC/x265** lorsque le tracker propose l’alternative pour la même œuvre.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('VVC', 'Détecte **VVC / H.266 / MPEG-I Part 8** encore rare sur les cercles français mais signalé lorsqu’un encodeur avant-gardiste l’emploie — léger bonus ou neutre suivant vos profils 4K (ici souvent léger positif résiduel lorsque vos lecteurs peuvent décoder HW).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Xvid', 'Détecte le codec ancien **`Xvid` / MPEG-4 ASP legacy** encore présent sur certains DVDsrip SD voire anciens épisodes télé. Score souvent très négatif sur profils HD/4K (« -500 ») pour pousser HEVC / AVC moderne trackers privés.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('h265', 'Mentions génériques **h265 / H265 / HEVC** annoncées sur la ligne titre (alternative orthographique **x265**).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('x264 (2160p)', '**x264 uniquement lorsque la ligne annonce également 2160p** (« x264 fake 4K » typique) pour les **bloquer** ou les **noter très négativement** alors que vos profils 4K préfèrent HEVC propre (« x264 @ UHD », voir également CF dédiée `x264 (2160p)` combinée suivant vos YAML profils Films/Séries anime).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('x265', 'Détecte l’empreinte **Encodeur logiciel « x265 »** dans le titre (variante très répandue dans la scene FR/US). Fonctionnement aligné avec `h265` / `HEVC` pour répartir vos bonus codecs selon la graphie exactement rencontrée sur les indexeurs.', 0);
