-- ops/09 — Delays / bundles complémentaires (ex. delay Sonarr si non dans 07)
-- Pas de fichier ops/08 dans le schéma 1.1.0.
--
-- INSERT INTO delay_profiles (name, preferred_protocol, usenet_delay, torrent_delay,
--   bypass_if_highest_quality, bypass_if_above_custom_format_score, minimum_custom_format_score)
-- VALUES ('Mon-Delay-Sonarr', 'prefer_usenet', 0, 0, 1, 0, NULL);
