-- french-profilarr-database — ops/03
-- Custom formats Radarr + Sonarr (include_in_rename = 0, repacks via FR-Repack*).

INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('3D', 'Contenu stéréoscopique 3D. Malus : peu d’installations 3D actives.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('AAC', 'Codec audio AAC dans le titre. Exclusions pour éviter le double-score audio.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('AV1', 'Codec AV1. Score -999999 sur tous les profils FR (compatibilité matériel).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Atmos', 'Dolby Atmos (ATMOS, DDPA, TrueHD.A) via FR-Regex-Atmos-Bundle.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS-ES', 'DTS-ES dans le titre. Exclusions vers les autres codecs du pack audio.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS-HD HRA', 'DTS-HD High Resolution. Exclusions pour une seule famille DTS par release.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS-HD MA', 'DTS-HD Master Audio. Exclusions TrueHD, DTS:X, FLAC, etc.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS-X', 'DTS:X objet. Une seule famille DTS premium par titre.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('DTS', 'DTS classique (non HD). Exclu si DTS-HD ou DTS:X présents.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Dolby Digital +', 'Dolby Digital Plus (E-AC-3). Exclusions audio mutualisées.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Dolby Digital', 'Dolby Digital (AC-3). Exclusions vers DTS/TrueHD du même pack.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Dolby Vision (Without Fallback)', 'DV sans HDR10 de secours lisible. Malus compatibilité lecteurs.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Dolby Vision', 'DV, DoVi, Dolby Vision. Exclut les combinaisons DV+HLG/SDR triviales.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FLAC', 'Piste FLAC. Exclusions si d’autres codecs audio dominent sur la même ligne.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-4KLight', 'Tag 4KLight (Bluray UHD allégé). Fort bonus sur profils 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Blockers', 'Groupes bannis, GPU encode (NVENC/QSV/AMF), incohérences REMUX+encodeur. Score très négatif.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-HDLight', 'Tag HDLight (Bluray allégé). Utile 720p/1080p ; rare en 2160p.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Hybrid', 'Tag HYBRID (Bluray hybride UHD). Bonus modéré si annoncé.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-MULTI-VF2', 'MULTI + VF2 (dual FR+QC). Meilleur palier langue.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-MULTI-VFF', 'MULTI + précision FR C411 (VFF, VOF, VFI, TRUEFRENCH, MULTI.FRENCH). Pas de MULTI seul.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-MULTI-VFQ', 'MULTI + VFQ/VOQ/CA (Québec). Repli sous VFF seul.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-MULTI-ambig', 'MULTI seul : plusieurs langues dont FR, sous-tag FR absent (indexeurs hors C411).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Repack-2', 'PROPER2 / REPACK2 ou REAL puis PROPER. Bonus au-dessus de FR-Repack.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Repack-3', 'PROPER3 / REPACK3. Bonus repack maximal.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Repack', 'PROPER, REPACK, RERIP ou REAL simple. Media en doNotPrefer ; le score CF décide.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-WEBRip', 'Tag WEBRip dans le titre. Malus léger profils 4K (C411 : WEB-DL untouched prioritaire).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Streamer-Premium', 'WEB premium (Netflix, Prime, Disney+, Apple TV+, HBO, Paramount+). Bonus modéré.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Streamer-Standard', 'WEB secondaires (NOW, Crunchyroll, iTunes). Utile animé et achats Apple.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-AMEN', 'Équipe AMEN — WEB 2160p compact DV/HDR10+. Bonus équipe.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-BONBON', 'Équipe BONBON — 4KLight / WEBRip compact. Fort bonus 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-BOUC', 'Équipe BOUC — WEB 2160p premium DV/HDR10+. Bonus modéré.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-ENIGMA', 'Équipe ENIGMA — WEB 1080p/2160p, catalogue VFQ/MULTI.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-FW', 'Équipe Forward — WEB 2160p volume. Bonus intermédiaire.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-HYPERION', 'Équipe HYPERION — surtout Remux. Remux à -999999 : jamais retenue.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-OZEF', 'Équipe OZEF — Remux Blu-ray/UHD. Remux exclu (-999999).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-PopHD', 'Équipe PopHD — 1080p HDLight x264, MULTI. Bonus 720p/1080p.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-QTZ', 'Équipe QTZ — référence 4KLight. Parmi les plus hauts scores team.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-SUPPLY', 'Équipe SUPPLY — WEB 2160p premium H265/DV/Atmos. Fort bonus 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-Slay3R', 'Équipe Slay3R — WEB 1080p/2160p/720p C411 (H264/H265, exclus).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-TFA', 'Équipe TFA — WEB 2160p MULTI. Bonus intermédiaire-haut.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-THESYNDiCATE', 'Équipe THESYNDiCATE — WEB 2160p HEVC. AV1 toujours exclu.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-TOXIC', 'Équipe TOXIC — 1080p HDLight. Souvent cumul FR-HDLight.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-TyHD', 'Équipe TyHD — WEB 2160p HEVC compact. Bonus modéré 4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Team-Winks', 'Équipe Winks — 1080p BluRay/WEB x265 MULTI (~4–5,5 Go). Référence C411.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Tier-01', 'Palier 01 encodeurs (BOUBA, NEOSTARK, …). Sous les équipes FR-Team.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-Tier-02', 'Palier 02 encodeurs (TLC, DFE, KPORAL, …). Sous FR-Tier-01.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-VF2', 'VF2 seul (dual FR+QC) sans MULTI. Au-dessus de VFF.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-VFF', 'Tag FR France (VFF, TRUEFRENCH, …) sans MULTI. Au-dessus du Québec.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-VFQ', 'VFQ/VOQ/CA sans MULTI. Repli Québec sous VFF.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('FR-VOSTFR', 'VOSTFR, SUBFRENCH, FANSUB, FASTSUB. Repli si pas de doublage FR.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Full Disc', 'Image disque complète (ISO, BDMV). Exclut WEB/Remux/encodes sur la même ligne.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('HDR', 'HDR générique hors HDR10/HDR10+ déjà gérés. Évite le double-score HDR.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('HDR10+', 'HDR10+ / HDR10 PLUS. Exclusions SDR, PQ, HLG.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('HDR10', 'HDR10 strict (sans Plus). Complète DV et HDR générique.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('IMAX Enhanced', 'IMAX Enhanced (Disney+, Bravia Core). Distinct du CF IMAX seul.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('IMAX', 'IMAX classique. Exclut IMAX Enhanced (regex dédiée).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Opus', 'Piste Opus. Ajuster le score si faux positif sur un release group.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('PCM', 'PCM/LPCM. Exclusions audio mutualisées.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Remux', 'Release Remux. Score -999999 sur tous les profils FR — encodes seulement.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Season Pack', 'Season Pack Sonarr. Petit bonus saison complète.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Theatrical', 'Édition Theatrical. IMAX géré par les CF dédiés.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('TrueHD', 'Dolby TrueHD. Exclusions DTS/FLAC du pack Dictionarry.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('UHD Bluray', 'Downscale 1080p depuis source UHD + HDR. Tout groupe peut déclencher le bonus.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Upscaled', 'Upscale, regrade ou AIUS. Blocage -999999 sur tous les profils FR.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('VP9', 'VP9 dans le titre. Malus léger : privilégier HEVC si disponible.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('VVC', 'VVC / H.266 rare. Bonus léger ou neutre selon décodage HW.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('Xvid', 'Xvid legacy SD. Malus fort sur profils HD/4K.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('h265', 'Mentions h265 / HEVC (orthographes alternatives à x265).', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('x264 (2160p)', 'x264 annoncé avec 2160p (faux 4K). Bloqué ou très mal noté en UHD.', 0);
INSERT INTO custom_formats (name, description, include_in_rename) VALUES ('x265', 'Encodeur x265 dans le titre. Aligné avec h265/HEVC.', 0);
