-- Generated for Profilarr v2 — regression tests (parser UI)
-- French Profilarr Database
-- Sources: anciens tests YAML (git 4d06891^), ROADMAP, captures qBit/Momie/slots
-- 457 titres de release réels
-- Regenerate: python3 scripts/generate_cf_tests_sql.py  (puis normalize_fr_metadata.py si besoin)

INSERT INTO custom_format_tests (custom_format_name, title, type, should_match, description)
VALUES
    ('3D', 'Movie.2024.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — 3D : ne doit pas correspondre (release réelle)'),
    ('3D', 'Movie.2024.1080p.bluray3d.x264-GROUP', 'movie', 1, 'Test parser — 3D : doit correspondre (release réelle)'),
    ('AAC', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — AAC : doit correspondre (release réelle)'),
    ('AAC', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — AAC : ne doit pas correspondre (release réelle)'),
    ('AAC', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — AAC : doit correspondre (release réelle)'),
    ('AAC', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — AAC : ne doit pas correspondre (release réelle)'),
    ('AAC', 'Film.AC3.2.0.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — AAC : ne doit pas correspondre (release réelle)'),
    ('AAC', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — AAC : ne doit pas correspondre (release réelle)'),
    ('AAC', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — AAC : doit correspondre (release réelle)'),
    ('AAC', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — AAC : doit correspondre (release réelle)'),
    ('AAC', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — AAC : doit correspondre (release réelle)'),
    ('AAC', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — AAC : ne doit pas correspondre (release réelle)'),
    ('AAC', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — AAC : ne doit pas correspondre (release réelle)'),
    ('AAC', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — AAC : doit correspondre (release réelle)'),
    ('AAC', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — AAC : doit correspondre (release réelle)'),
    ('AAC', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — AAC : ne doit pas correspondre (release réelle)'),
    ('AV1', 'Arcane S01 2160p UHD BluRay DD 5.1 DV HDR AV1-TiZU', 'series', 1, 'Test parser — AV1 : doit correspondre (release réelle)'),
    ('AV1', 'Destins.croises.2026.MULTI.VFF.2160p.WEBRiP.DV.HDR.EAC3.5.1.AV1-THESYNDiCATE', 'movie', 1, 'Test parser — AV1 : doit correspondre — THESYNDiCATE AV1'),
    ('AV1', 'Up.2009.2160p.Bluray.AC3.HDR.DV.AV1-TiZU.mkv', 'movie', 1, 'Test parser — AV1 : doit correspondre (release réelle)'),
    ('Atmos', 'Film.2024.1080p.WEB-DL.DD.5.1.x264-GROUP', 'movie', 0, 'Test parser — Atmos : ne doit pas correspondre (release réelle)'),
    ('Atmos', 'The Last of Us S01 2160p MAX WEB-DL DDP 5.1 Atmos DV HDR H.265-FLUX', 'series', 1, 'Test parser — Atmos : doit correspondre (release réelle)'),
    ('Atmos', 'The.Last.of.Us.S01.2160p.UHD.BluRay.Remux.TrueHDA7.1.H.265-PmP', 'series', 1, 'Test parser — Atmos : doit correspondre (release réelle)'),
    ('DTS', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS', 'Film.AC3.2.0.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS', 'Film.DTS-HD.MA.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Film.DTS-X.7.1.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Film.dts.es.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS', 'Movie.DTS-X.7.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS', 'Movie.DTS-X.7.1.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Movie.DTS.WEB-DL.x264-GROUP', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS : doit correspondre (release réelle)'),
    ('DTS', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS : ne doit pas correspondre (release réelle)'),
    ('DTS-ES', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — DTS-ES : doit correspondre (release réelle)'),
    ('DTS-ES', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS-ES : ne doit pas correspondre (release réelle)'),
    ('DTS-ES', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — DTS-ES : doit correspondre (release réelle)'),
    ('DTS-ES', 'Film.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-ES : ne doit pas correspondre (release réelle)'),
    ('DTS-ES', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-ES : ne doit pas correspondre (release réelle)'),
    ('DTS-ES', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-ES : ne doit pas correspondre (release réelle)'),
    ('DTS-ES', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-ES : doit correspondre (release réelle)'),
    ('DTS-ES', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-ES : doit correspondre (release réelle)'),
    ('DTS-ES', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — DTS-ES : doit correspondre (release réelle)'),
    ('DTS-ES', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS-ES : ne doit pas correspondre (release réelle)'),
    ('DTS-ES', 'Movie.DTS-ES.DD5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-ES : doit correspondre (release réelle)'),
    ('DTS-ES', 'Movie.DTS-X.7.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-ES : ne doit pas correspondre (release réelle)'),
    ('DTS-ES', 'Movie.DTS-X.7.1.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-ES : doit correspondre (release réelle)'),
    ('DTS-ES', 'Movie.DTS.WEB-DL.x264-GROUP', 'movie', 0, 'Test parser — DTS-ES : ne doit pas correspondre (release réelle)'),
    ('DTS-ES', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS-ES : ne doit pas correspondre (release réelle)'),
    ('DTS-ES', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS-ES : doit correspondre (release réelle)'),
    ('DTS-ES', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS-ES : doit correspondre (release réelle)'),
    ('DTS-ES', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS-ES : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Film.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Film.DTS-HD.HRA.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Movie.DTS-ES.DD5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Movie.DTS-X.7.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Movie.DTS-X.7.1.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Movie.DTS.WEB-DL.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD HRA', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS-HD HRA : doit correspondre (release réelle)'),
    ('DTS-HD HRA', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS-HD HRA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD MA', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — DTS-HD MA : doit correspondre (release réelle)'),
    ('DTS-HD MA', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD MA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD MA', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — DTS-HD MA : doit correspondre (release réelle)'),
    ('DTS-HD MA', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD MA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD MA', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD MA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD MA', 'Film.DTS-HD.MA.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD MA : doit correspondre (release réelle)'),
    ('DTS-HD MA', 'Film.DTS-X.7.1.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD MA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD MA', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD MA : doit correspondre (release réelle)'),
    ('DTS-HD MA', 'Film.dts.es.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD MA : doit correspondre (release réelle)'),
    ('DTS-HD MA', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD MA : doit correspondre (release réelle)'),
    ('DTS-HD MA', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD MA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD MA', 'Movie.DTS-X.7.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD MA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD MA', 'Movie.DTS-X.7.1.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-HD MA : doit correspondre (release réelle)'),
    ('DTS-HD MA', 'Movie.DTS.WEB-DL.x264-GROUP', 'movie', 0, 'Test parser — DTS-HD MA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD MA', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS-HD MA : ne doit pas correspondre (release réelle)'),
    ('DTS-HD MA', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS-HD MA : doit correspondre (release réelle)'),
    ('DTS-HD MA', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS-HD MA : doit correspondre (release réelle)'),
    ('DTS-HD MA', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS-HD MA : ne doit pas correspondre (release réelle)'),
    ('DTS-X', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — DTS-X : doit correspondre (release réelle)'),
    ('DTS-X', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS-X : ne doit pas correspondre (release réelle)'),
    ('DTS-X', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — DTS-X : doit correspondre (release réelle)'),
    ('DTS-X', 'Film.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-X : ne doit pas correspondre (release réelle)'),
    ('DTS-X', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-X : ne doit pas correspondre (release réelle)'),
    ('DTS-X', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — DTS-X : ne doit pas correspondre (release réelle)'),
    ('DTS-X', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-X : doit correspondre (release réelle)'),
    ('DTS-X', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-X : doit correspondre (release réelle)'),
    ('DTS-X', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — DTS-X : doit correspondre (release réelle)'),
    ('DTS-X', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — DTS-X : ne doit pas correspondre (release réelle)'),
    ('DTS-X', 'Movie.DTS-X.7.1.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — DTS-X : doit correspondre (release réelle)'),
    ('DTS-X', 'Movie.DTS.WEB-DL.x264-GROUP', 'movie', 0, 'Test parser — DTS-X : ne doit pas correspondre (release réelle)'),
    ('DTS-X', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS-X : ne doit pas correspondre (release réelle)'),
    ('DTS-X', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS-X : doit correspondre (release réelle)'),
    ('DTS-X', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — DTS-X : doit correspondre (release réelle)'),
    ('DTS-X', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — DTS-X : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — Dolby Digital : doit correspondre (release réelle)'),
    ('Dolby Digital', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — Dolby Digital : doit correspondre (release réelle)'),
    ('Dolby Digital', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital', 'Film.AC3.2.0.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — Dolby Digital : doit correspondre (release réelle)'),
    ('Dolby Digital', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — Dolby Digital : doit correspondre (release réelle)'),
    ('Dolby Digital', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — Dolby Digital : doit correspondre (release réelle)'),
    ('Dolby Digital', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — Dolby Digital : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — Dolby Digital : doit correspondre (release réelle)'),
    ('Dolby Digital', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — Dolby Digital : doit correspondre (release réelle)'),
    ('Dolby Digital', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — Dolby Digital : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital +', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — Dolby Digital + : doit correspondre (release réelle)'),
    ('Dolby Digital +', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital + : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital +', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — Dolby Digital + : doit correspondre (release réelle)'),
    ('Dolby Digital +', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital + : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital +', 'Film.AC3.2.0.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital + : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital +', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital + : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital +', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — Dolby Digital + : doit correspondre (release réelle)'),
    ('Dolby Digital +', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — Dolby Digital + : doit correspondre (release réelle)'),
    ('Dolby Digital +', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — Dolby Digital + : doit correspondre (release réelle)'),
    ('Dolby Digital +', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — Dolby Digital + : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital +', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — Dolby Digital + : ne doit pas correspondre (release réelle)'),
    ('Dolby Digital +', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — Dolby Digital + : doit correspondre (release réelle)'),
    ('Dolby Vision', 'Film.2024.2160p.UHD.BluRay.DV.HLG.HDR.x265-GROUP', 'movie', 0, 'Test parser — Dolby Vision : ne doit pas correspondre (release réelle)'),
    ('Dolby Vision', 'Film.2024.2160p.UHD.BluRay.Dolby.Vision.HDR.x265-GROUP', 'movie', 1, 'Test parser — Dolby Vision : doit correspondre (release réelle)'),
    ('Dolby Vision (Without Fallback)', 'Barbie (2023) (2160p AMZN WEB-DL Hybrid H265 DV HDR10+ DDP Atmos 5.1 English - HONE)', 'movie', 0, 'Test parser — Dolby Vision (Without Fallback) : ne doit pas correspondre (release réelle)'),
    ('Dolby Vision (Without Fallback)', 'Barbie.2023.2160p.MA.WEB-DL.DDP5.1.Atmos.DV.H.265-FLUX', 'movie', 1, 'Test parser — Dolby Vision (Without Fallback) : doit correspondre (release réelle)'),
    ('Dolby Vision (Without Fallback)', 'Barbie.2023.2160p.MA.WEB-DL.DDP5.1.Atmos.DV.H.265-FLUX.mkv', 'movie', 1, 'Test parser — Dolby Vision (Without Fallback) : doit correspondre (release réelle)'),
    ('Dolby Vision (Without Fallback)', 'Barbie.2023.2160p.MA.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-FLUX', 'movie', 0, 'Test parser — Dolby Vision (Without Fallback) : ne doit pas correspondre (release réelle)'),
    ('Dolby Vision (Without Fallback)', 'Killers of the Flower Moon (2023) {tmdb-466420} [iT][WEBDL-2160p][DV HDR10Plus][EAC3 Atmos 5.1][h265]-FLUX.mkv', 'movie', 0, 'Test parser — Dolby Vision (Without Fallback) : ne doit pas correspondre (release réelle)'),
    ('FLAC', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — FLAC : doit correspondre (release réelle)'),
    ('FLAC', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — FLAC : ne doit pas correspondre (release réelle)'),
    ('FLAC', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — FLAC : doit correspondre (release réelle)'),
    ('FLAC', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — FLAC : ne doit pas correspondre (release réelle)'),
    ('FLAC', 'Film.AC3.2.0.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — FLAC : ne doit pas correspondre (release réelle)'),
    ('FLAC', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — FLAC : ne doit pas correspondre (release réelle)'),
    ('FLAC', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — FLAC : doit correspondre (release réelle)'),
    ('FLAC', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — FLAC : doit correspondre (release réelle)'),
    ('FLAC', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — FLAC : doit correspondre (release réelle)'),
    ('FLAC', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — FLAC : ne doit pas correspondre (release réelle)'),
    ('FLAC', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — FLAC : ne doit pas correspondre (release réelle)'),
    ('FLAC', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — FLAC : doit correspondre (release réelle)'),
    ('FLAC', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — FLAC : doit correspondre (release réelle)'),
    ('FLAC', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — FLAC : ne doit pas correspondre (release réelle)'),
    ('FR-4KLight', '1917.2019.MULTI.VFF.2160p.BluRay.4KLight.HDR10Plus.TrueHD.7.1.Atmos.x265-QTZ', 'movie', 1, 'Test parser — FR-4KLight : doit correspondre (release réelle)'),
    ('FR-4KLight', 'Annabelle.2014.MULTI.VFF.WebRip.2160p.10bit.4KLight.HDR.AC3.x265-BONBON', 'movie', 1, 'Test parser — FR-4KLight : doit correspondre (release réelle)'),
    ('FR-4KLight', 'Captain.America.First.Avenger.2011.MULTi.VF2.2160p.HYBRID.UHD.BluRay.REMUX.DV.HDR10.TrueHD.7.1.HEVC-TTK', 'movie', 0, 'Test parser — FR-4KLight : ne doit pas correspondre (release réelle)'),
    ('FR-4KLight', 'Caught.Stealing.2025.MULTI.VF2.2160p.WEB.DV.HDR10Plus.AC3.5.1.H265-Slay3R', 'movie', 0, 'Test parser — FR-4KLight : ne doit pas correspondre (release réelle)'),
    ('FR-4KLight', 'Film.2024.MULTI.VFF.2160p.UHD.BluRay.4K.Light.HDR10.x265-QTZ', 'movie', 1, 'Test parser — FR-4KLight : doit correspondre (release réelle)'),
    ('FR-4KLight', 'Trois.couleurs.Blanc.1994.VOF.2160p.BluRay.4KLight.DV.AC3.5.1.x265-QTZ', 'movie', 1, 'Test parser — FR-4KLight : doit correspondre (release réelle)'),
    ('FR-Blockers', 'Anime.S01E04.VOSTFR.1080p.BDRip.AAC.x264-Firesoul64', 'series', 0, 'Test parser — FR-Blockers : ne doit pas correspondre (release réelle)'),
    ('FR-Blockers', 'Film.2015.FRENCH.BDRip.x264-k0RE', 'movie', 1, 'Test parser — FR-Blockers : doit correspondre (release réelle)'),
    ('FR-Blockers', 'Film.2023.MULTI.VFF.UHD.2160p.DTS-X.x265-TFA', 'movie', 0, 'Test parser — FR-Blockers : ne doit pas correspondre (release réelle)'),
    ('FR-Blockers', 'Film.2024.1080p.WEB-DL.x264-FGT', 'movie', 1, 'Test parser — FR-Blockers : doit correspondre (release réelle)'),
    ('FR-Blockers', 'Film.2024.MULTI.VFF.1080p.WEBRip.H264-TEAM', 'movie', 0, 'Test parser — FR-Blockers : ne doit pas correspondre (release réelle)'),
    ('FR-Blockers', 'Film.2024.MULTI.VFF.1080p.WEBRip.H264.NVENC-TEAM', 'movie', 1, 'Test parser — FR-Blockers : doit correspondre (release réelle)'),
    ('FR-Blockers', 'Film.2024.YIFY.1080p.WEB-DL.x264', 'movie', 1, 'Test parser — FR-Blockers : doit correspondre (release réelle)'),
    ('FR-Blockers', 'Pack.Serie.VOSTFR.x264-Wawacity', 'movie', 1, 'Test parser — FR-Blockers : doit correspondre (release réelle)'),
    ('FR-Blockers', 'WALL.E.2008.MULTI.VFF.2160p.UHD.BluRay.REMUX.DV.HDR10PLUS.TrueHD.7.1.HEVC-NOTAG', 'movie', 0, 'Test parser — FR-Blockers : ne doit pas correspondre (release réelle)'),
    ('FR-Blockers', 'WALL.E.2008.MULTI.VFF.2160p.UHD.BluRay.REMUX.DV.HDR10PLUS.TrueHD.7.1.x265-NOTAG', 'movie', 1, 'Test parser — FR-Blockers : doit correspondre (release réelle)'),
    ('FR-HDLight', 'Alita.Battle.Angel.2019.MULTI.VFF.1080p.BluRay.DTS.HD.MA.7.1.x264-RiFiFi', 'movie', 0, 'Test parser — FR-HDLight : ne doit pas correspondre (release réelle)'),
    ('FR-HDLight', 'Caught.Stealing.2025.MULTI.VF2.2160p.WEB.DV.HDR10Plus.AC3.5.1.H265-Slay3R', 'movie', 0, 'Test parser — FR-HDLight : ne doit pas correspondre (release réelle)'),
    ('FR-HDLight', 'Deadpool.2016.MULTI.VFF.1080p.BluRay.HDLight.AC3.5.1.x264-PopHD', 'movie', 1, 'Test parser — FR-HDLight : doit correspondre — HDLight PopHD'),
    ('FR-HDLight', 'La.Rose.De.La.Mer.1946.VFF.1080p.HDLight.AC3.2.0.H264-NOTAG', 'movie', 1, 'Test parser — FR-HDLight : doit correspondre (release réelle)'),
    ('FR-HDLight', 'La.Soupe.aux.choux.1981.VFF.1080p.BluRay.HDLight.AAC.2.0.x265-NOTAG', 'movie', 1, 'Test parser — FR-HDLight : doit correspondre (release réelle)'),
    ('FR-HDLight', 'Le.Sillage.De.La.Violence.1965.MULTI.VFI.1080p.HDLight.AC3.2.0.x264-NOTAG', 'movie', 1, 'Test parser — FR-HDLight : doit correspondre (release réelle)'),
    ('FR-Hybrid', 'Alien.1979.HYBRID.2160p.BluRay.REMUX.HEVC.DV-HDR10Plus.DTS-HD.MA.5.1', 'movie', 1, 'Test parser — FR-Hybrid : doit correspondre (release réelle)'),
    ('FR-Hybrid', 'Captain.America.First.Avenger.2011.MULTi.VF2.2160p.HYBRID.UHD.BluRay.REMUX.DV.HDR10.TrueHD.7.1.HEVC-TTK', 'movie', 1, 'Test parser — FR-Hybrid : doit correspondre (release réelle)'),
    ('FR-Hybrid', 'Caught.Stealing.2025.MULTI.VF2.2160p.WEB.DV.HDR10Plus.AC3.5.1.H265-Slay3R', 'movie', 0, 'Test parser — FR-Hybrid : ne doit pas correspondre (release réelle)'),
    ('FR-Hybrid', 'Film.2024.MULTI.VFF.2160p.UHD.BluRay.REMUX.DV.HDR10.HEVC-TFA', 'movie', 0, 'Test parser — FR-Hybrid : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'F1.Le.Film.2025.MULTITRUEFRENCH.2160p.WEB.x265-Slay3R', 'movie', 1, 'Test parser — FR-MULTI-VF2 : doit correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Film.2018.MULTI.VFF.Bluray.1080p.DTS.5.1.x264-AMEN', 'movie', 0, 'Test parser — FR-MULTI-VF2 : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Film.2019.VFF.BDRip.1080p.x264-OZEF', 'movie', 0, 'Test parser — FR-MULTI-VF2 : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Film.2021.MULTI.VF2.UHD.2160p.DoVi.HDR10Plus.x265-TFA', 'movie', 1, 'Test parser — FR-MULTI-VF2 : doit correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Film.2022.MULTI.VFF.UHD.2160p.WEB-DL.h265-GKS', 'movie', 1, 'Test parser — FR-MULTI-VF2 : doit correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Film.2022.MULTI.VOQ.2160p.BluRay.x265-QTZ', 'movie', 1, 'Test parser — FR-MULTI-VF2 : doit correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Film.2024.MULTi.VF2.WEB-DL.1080p.h264-TFA', 'movie', 1, 'Test parser — FR-MULTI-VF2 : doit correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Film.2024.VOSTFR.WEB-DL.1080p.x264-TEAM', 'movie', 0, 'Test parser — FR-MULTI-VF2 : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Incendies.2010.VOQ.2160p.BluRay.DDP.x265-QTZ', 'movie', 0, 'VOQ seul sans MULTI — ne doit pas matcher FR-MULTI-VF2'),
    ('FR-MULTI-VF2', 'Incendies.2010.MULTI.VOQ.2160p.BluRay.DDP.x265-QTZ', 'movie', 1, 'MULTI + VOQ — doit matcher FR-MULTI-VF2'),
    ('FR-MULTI-VF2', 'MultiVerse.2024.1080p.WEB-DL.x265-GROUP', 'movie', 0, 'Test parser — FR-MULTI-VF2 : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Person.Of.Interest.S01.MULTI.FRENCH.1080p.WEBRip.x265-DELIRIUS', 'series', 1, 'Test parser — FR-MULTI-VF2 : doit correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Serie.S02E01.FRENCH.MULTI.1080p.WEB.h264-QTZ', 'series', 1, 'Test parser — FR-MULTI-VF2 : doit correspondre (release réelle)'),
    ('FR-MULTI-VF2', 'Serie.S03E10.VFQ.WEB.1080p.EAC3.5.1.h264-FW', 'series', 1, 'Test parser — FR-MULTI-VF2 : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Apex.2026.MULTI.FRENCH.1080p.WEBRip.x265-GROUP', 'movie', 1, 'qBit Apex'),
    ('FR-MULTI-VFF', 'F1.Le.Film.2025.MULTITRUEFRENCH.2160p.WEB.EAC3.5.1.x265-Slay3R', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'F1.Le.Film.2025.MULTITRUEFRENCH.2160p.WEB.x265-Slay3R', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Film.2019.VFF.BDRip.1080p.x264-OZEF', 'movie', 0, 'Test parser — FR-MULTI-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Film.2020.VFQ.WEB-DL.1080p.h264-AMEN', 'movie', 0, 'Test parser — FR-MULTI-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Film.2022.MULTI.VFF.UHD.2160p.WEB-DL.h265-GKS', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Film.2022.MULTI.VFI.WEB-DL.1080p.h264-TEAM', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Film.2023.MULTI.VFF.Bluray.1080p.DTS-HD.MA.5.1.x264-TFA', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Film.2024.FRENCH.SUBS.1080p.WEB-DL.x264-TEAM', 'movie', 0, 'Test parser — FR-MULTI-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Film.2024.MULTi.VF2.WEB-DL.1080p.h264-TFA', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Film.2024.VOSTFR.WEB-DL.1080p.x264-TEAM', 'movie', 0, 'Test parser — FR-MULTI-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Incendies.2010.VOQ.2160p.BluRay.DDP.x265-QTZ', 'movie', 0, 'Test parser — FR-MULTI-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'La.Momie.1999.MULTI.TRUEFRENCH.2160p.WEB.DV.HDR.DV.WEB-DL.H265-Slay3R', 'movie', 1, 'Capture — Momie TRUEFRENCH'),
    ('FR-MULTI-VFF', 'La.Momie.1999.MULTI.VFF.2160p.WEB.DV.HDR10PLUS.AC3.5.1.H265-Slay3R', 'movie', 1, 'Capture — Momie tags complets'),
    ('FR-MULTI-VFF', 'M3GAN.2.0.2025.MULTI.FRENCH.2160p.WEB.H265-GROUP', 'movie', 1, 'qBit M3GAN 2.0'),
    ('FR-MULTI-VFF', 'MultiVerse.2024.1080p.WEB-DL.x265-GROUP', 'movie', 0, 'Test parser — FR-MULTI-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'NCIS.Los.Angeles.S14.MULTI.FRENCH.1080p.WEBRip.x265-GROUP', 'series', 1, 'qBit NCIS'),
    ('FR-MULTI-VFF', 'Person.Of.Interest.S01.MULTI.FRENCH.1080p.WEBRip.x265-DELIRIUS', 'series', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Person.Of.Interest.S05.MULTI.FRENCH.1080p.WEBRip.x265-DELIRIUS', 'series', 1, 'qBit cross-seed POI S05'),
    ('FR-MULTI-VFF', 'Sept.Ecossais.Du.Texas.1966.MULTI.VF.1080p.WEBRip.AC3.2.0.x264-NOTAG', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Serie.S01E04.TRUEFRENCH.WEB.720p.x264-FW', 'series', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Serie.S02E01.FRENCH.MULTI.1080p.WEB.h264-QTZ', 'series', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Serie.S03E10.VF2.WEB.1080p.EAC3.5.1.h264-FW', 'series', 0, 'Test parser — FR-MULTI-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'The.Bear.S04.MULTI.VOF.1080p.WEB.EAC3.5.1.H264-TFA', 'series', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Top.Gun.1986.MULTI.VFI.2160p.BluRay.DolbyVision.Atmos.5.1.x265-QTZ', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Twisters.2024.VFB.2160p.WEB.HDR.EAC3.5.1.H265-FW', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-MULTI-VFF', 'Uncharted.2022.MULTI.VFF.2160p.BluRay.DV.EAC3.7.1.x265-QTZ', 'movie', 1, 'Test parser — FR-MULTI-VFF : doit correspondre (release réelle)'),
    ('FR-Repack', 'Film.2024.MULTI.VFF.1080p.WEB-DL.x264-TEAM', 'movie', 0, 'Test parser — FR-Repack : ne doit pas correspondre (release réelle)'),
    ('FR-Repack', 'Sonic.the.Hedgehog.3.2024.REPACK.2160p.WEB-DL.DDP5.1.Atmos.DoVi.HDR.H.265-FLUX', 'movie', 1, 'Test parser — FR-Repack : doit correspondre (release réelle)'),
    ('FR-Repack', 'Sonic.the.Hedgehog.3.2024.REPACK3.2160p.WEB-DL.DDP5.1.Atmos.DoVi.HDR.H.265-FLUX', 'movie', 0, 'Test parser — FR-Repack : ne doit pas correspondre (release réelle)'),
    ('FR-Repack', 'The.Zone.of.Interest.2023.PROPER.2160p.UHD.BluRay.TrueHD.7.1.Atmos.HDR.x265-MainFrame', 'movie', 1, 'Test parser — FR-Repack : doit correspondre (release réelle)'),
    ('FR-Repack', 'Yo-Kai.Watch.S02E17.DUBBED.REAL.REPACK.HDTV.x264-W4F', 'series', 1, 'Test parser — FR-Repack : doit correspondre (release réelle)'),
    ('FR-Repack', 'roommate.wanted.2015.rerip.720p.bluray.x264-rusted', 'movie', 1, 'Test parser — FR-Repack : doit correspondre (release réelle)'),
    ('FR-Repack-2', 'Release.2024.REPACK2.1080p.WEB-DL.x264-GROUP', 'movie', 1, 'Test parser — FR-Repack-2 : doit correspondre (release réelle)'),
    ('FR-Repack-2', 'Scene.Show.S01E01.REAL.PROPER.1080p.WEB.h264-GROUP', 'series', 1, 'Test parser — FR-Repack-2 : doit correspondre (release réelle)'),
    ('FR-Repack-2', 'Sonic.the.Hedgehog.3.2024.REPACK3.2160p.WEB-DL.DDP5.1.Atmos.DoVi.HDR.H.265-FLUX', 'movie', 0, 'Test parser — FR-Repack-2 : ne doit pas correspondre (release réelle)'),
    ('FR-Repack-2', 'The.Zone.of.Interest.2023.PROPER.2160p.UHD.BluRay.TrueHD.7.1.Atmos.HDR.x265-MainFrame', 'movie', 0, 'Test parser — FR-Repack-2 : ne doit pas correspondre (release réelle)'),
    ('FR-Repack-2', 'The.Zone.of.Interest.2023.PROPER2.2160p.UHD.BluRay.TrueHD.7.1.Atmos.HDR.x265-MainFrame', 'movie', 1, 'Test parser — FR-Repack-2 : doit correspondre (release réelle)'),
    ('FR-Repack-3', 'Film.2024.PROPER3.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — FR-Repack-3 : doit correspondre (release réelle)'),
    ('FR-Repack-3', 'Sonic.the.Hedgehog.3.2024.REPACK2.2160p.WEB-DL.DDP5.1.Atmos.DoVi.HDR.H.265-FLUX', 'movie', 0, 'Test parser — FR-Repack-3 : ne doit pas correspondre (release réelle)'),
    ('FR-Repack-3', 'Sonic.the.Hedgehog.3.2024.REPACK3.2160p.WEB-DL.DDP5.1.Atmos.DoVi.HDR.H.265-FLUX', 'movie', 1, 'Test parser — FR-Repack-3 : doit correspondre (release réelle)'),
    ('FR-Repack-3', 'The.Zone.of.Interest.2023.PROPER.2160p.UHD.BluRay.TrueHD.7.1.Atmos.HDR.x265-MainFrame', 'movie', 0, 'Test parser — FR-Repack-3 : ne doit pas correspondre (release réelle)'),
    ('FR-Streamer-Premium', 'Gladiator 2000 Paramount Reissue Extended Cut 1080p BluRay REMUX-FraMeSToR', 'movie', 0, 'Test parser — FR-Streamer-Premium : ne doit pas correspondre (release réelle)'),
    ('FR-Streamer-Premium', 'Men in Black 1997 2160p Apple TV+ WEB-DL DDP 5 1 Atmos DV H 265-CHDWEB', 'movie', 1, 'Test parser — FR-Streamer-Premium : doit correspondre (release réelle)'),
    ('FR-Streamer-Premium', 'The.Roast.of.Tom.Brady.2024.1080p.NF.WEB-DL.DDP5.1.H.264-NTb', 'movie', 1, 'Test parser — FR-Streamer-Premium : doit correspondre (release réelle)'),
    ('FR-Streamer-Standard', 'Show.S01E01.NOW.WEB-DL.x264-GROUP', 'series', 1, 'Test parser — FR-Streamer-Standard : doit correspondre (release réelle)'),
    ('FR-Streamer-Standard', 'Some.Movie.1080p.IT.WEB-DL.DDP5.1.x264-GROUP', 'movie', 1, 'Test parser — FR-Streamer-Standard : doit correspondre (release réelle)'),
    ('FR-Streamer-Standard', 'The 1975-iTunes Music Festival London (2013)-CONVERT-1080p-x264', 'movie', 0, 'Test parser — FR-Streamer-Standard : ne doit pas correspondre (release réelle)'),
    ('FR-Team-AMEN', 'Dangerous.Animals.2025.MULTI.VFQ.2160p.WEB.DV.AC3.5.1.x265-Amen', 'movie', 1, 'Test parser — FR-Team-AMEN : doit correspondre — ROADMAP AMEN'),
    ('FR-Team-AMEN', 'Film.2025.MULTI.VFQ.2160p.WEB.DV.AC3.5.1.x265-AMEN', 'movie', 1, 'Test parser — FR-Team-AMEN : doit correspondre (release réelle)'),
    ('FR-Team-AMEN', 'Film.2025.MULTI.VFQ.2160p.WEB.DV.AC3.5.1.x265-Amen', 'movie', 1, 'Test parser — FR-Team-AMEN : doit correspondre (release réelle)'),
    ('FR-Team-BONBON', 'Annabelle.2014.MULTI.VFF.WebRip.2160p.10bit.4KLight.HDR.AC3.x265-BONBON', 'movie', 1, 'Test parser — FR-Team-BONBON : doit correspondre (release réelle)'),
    ('FR-Team-BONBON', 'Film.2024.MULTI.VFF.UHD.2160p.DoVi.HDR10.DTS-X.x265-TFA', 'movie', 0, 'Test parser — FR-Team-BONBON : ne doit pas correspondre (release réelle)'),
    ('FR-Team-BONBON', 'Rose.Bonbon.1986.VFF.2160p.BluRay.AC3.2.0.x265-SOLO', 'movie', 0, 'Test parser — FR-Team-BONBON : ne doit pas correspondre (release réelle)'),
    ('FR-Team-BOUC', 'Agent.Zeta.2026.MULTI.VFF.2160p.WEB.DV.EAC3.5.1.H265-BOUC', 'movie', 1, 'Test parser — FR-Team-BOUC : doit correspondre (release réelle)'),
    ('FR-Team-BOUC', 'Film.2024.MULTI.VFF.1080p.WEB-DL.x264-SUPPLY', 'movie', 0, 'Test parser — FR-Team-BOUC : ne doit pas correspondre (release réelle)'),
    ('FR-Team-BOUC', 'Nature.predatrice.2026.MULTI.VFF.2160p.WEB.DV.EAC3.5.1.H265-BOUC', 'movie', 1, 'Test parser — FR-Team-BOUC : doit correspondre (release réelle)'),
    ('FR-Team-ENIGMA', 'Agent.Zeta.2026.MULTI.VFF.2160p.WEB.DV.EAC3.5.1.H265-BOUC', 'movie', 0, 'Test parser — FR-Team-ENIGMA : ne doit pas correspondre (release réelle)'),
    ('FR-Team-ENIGMA', 'Left.Behind.Rise.Of.The.Antichrist.2023.VOSTFR.1080p.WEB.EAC3.2.0.H265-Enigma', 'movie', 1, 'Test parser — FR-Team-ENIGMA : doit correspondre (release réelle)'),
    ('FR-Team-ENIGMA', 'Nightmare.Island.2020.MULTI.VFQ.2160p.WEB.SDR.AC3.5.1.H265-TyHD', 'movie', 0, 'Test parser — FR-Team-ENIGMA : ne doit pas correspondre (release réelle)'),
    ('FR-Team-ENIGMA', 'RoboCop.1987.MULTI.VFF.1080p.WEB.EAC3.5.1.H264-ENIGMA', 'movie', 1, 'Test parser — FR-Team-ENIGMA : doit correspondre (release réelle)'),
    ('FR-Team-ENIGMA', 'Shang.chi.et.la.legende.des.dix.anneaux.2021.MULTI.VF2.2160p.WEB.HDR10.EAC3.5.1.H265-ENIGMA', 'movie', 1, 'Test parser — FR-Team-ENIGMA : doit correspondre (release réelle)'),
    ('FR-Team-ENIGMA', 'Votez.Bougon.2016.VFQ.1080p.WEB.EAC3.5.1.H264-ENIGMA', 'movie', 1, 'Test parser — FR-Team-ENIGMA : doit correspondre (release réelle)'),
    ('FR-Team-FW', 'Film.2024.MULTI.VFF.UHD.2160p.DoVi.HDR10.DTS-X.x265-TFA', 'movie', 0, 'Test parser — FR-Team-FW : ne doit pas correspondre (release réelle)'),
    ('FR-Team-FW', 'Gary.2026.MULTI.VFF.2160p.HDR.DV.WEB.EAC3.5.1.H265-FW', 'movie', 1, 'Test parser — FR-Team-FW : doit correspondre (release réelle)'),
    ('FR-Team-FW', 'Halloween.Chez.Les.Loud.2023.MULTI.VFF.2160p.WEB.EAC3.2.0.H265-FW', 'movie', 1, 'Test parser — FR-Team-FW : doit correspondre (release réelle)'),
    ('FR-Team-HYPERION', 'Dune.Deuxieme.Partie.2024.REPACK.MULTI.VF2.2160p.UHD.BluRay.Remux.DV.HDR10Plus.TrueHD.Atmos.7.1.HEVC-HYPERION', 'movie', 1, 'Test parser — FR-Team-HYPERION : doit correspondre (release réelle)'),
    ('FR-Team-HYPERION', 'Matrix.1999.MULTI.VFI.2160p.UHD.BluRay.Remux.DV.HDR.TrueHD.Atmos.7.1.HEVC-HYPERION', 'movie', 1, 'Test parser — FR-Team-HYPERION : doit correspondre (release réelle)'),
    ('FR-Team-HYPERION', 'Shang.chi.et.la.legende.des.dix.anneaux.2021.MULTI.VF2.2160p.WEB.HDR10.EAC3.5.1.H265-ENIGMA', 'movie', 0, 'Test parser — FR-Team-HYPERION : ne doit pas correspondre (release réelle)'),
    ('FR-Team-HYPERION', 'Tetris.2023.AD.MULTI.VFI.2160p.WEB.DV.HDR10Plus.EAC3.5.1.HEVC-HYPERION', 'movie', 1, 'Test parser — FR-Team-HYPERION : doit correspondre (release réelle)'),
    ('FR-Team-OZEF', 'Agent.Zeta.2026.MULTI.VFF.2160p.WEB.DV.EAC3.5.1.H265-BOUC', 'movie', 0, 'Test parser — FR-Team-OZEF : ne doit pas correspondre (release réelle)'),
    ('FR-Team-OZEF', 'Hamnet.2025.MULTI.VFF.1080p.BLURAY.REMUX.TrueHD.7.1.AVC-OZEF', 'movie', 1, 'Test parser — FR-Team-OZEF : doit correspondre (release réelle)'),
    ('FR-Team-PopHD', 'Agent.Zeta.2026.MULTI.VFF.2160p.WEB.DV.EAC3.5.1.H265-BOUC', 'movie', 0, 'Test parser — FR-Team-PopHD : ne doit pas correspondre (release réelle)'),
    ('FR-Team-PopHD', 'Deadpool.2016.MULTI.VFF.1080p.BluRay.HDLight.AC3.5.1.x264-PopHD', 'movie', 1, 'Test parser — FR-Team-PopHD : doit correspondre (release réelle)'),
    ('FR-Team-PopHD', 'Matrix.1999.MULTI.VFF.1080p.BluRay.HDLight.AC3.5.1.x264-PopHD', 'movie', 1, 'Test parser — FR-Team-PopHD : doit correspondre (release réelle)'),
    ('FR-Team-QTZ', '1917.2019.MULTI.VFF.2160p.BluRay.4KLight.HDR10Plus.TrueHD.7.1.Atmos.x265-QTZ', 'movie', 1, 'Test parser — FR-Team-QTZ : doit correspondre — Slot 4KLight QTZ'),
    ('FR-Team-SUPPLY', 'Film.2024.MULTI.VFF.UHD.2160p.DoVi.HDR10.DTS-X.x265-TFA', 'movie', 0, 'Test parser — FR-Team-SUPPLY : ne doit pas correspondre (release réelle)'),
    ('FR-Team-SUPPLY', 'Predator.Badlands.2025.MULTI.VF2.2160p.WEB.DV.HDR10Plus.EAC3.Atmos.5.1.H265-SUPPLY', 'movie', 1, 'Test parser — FR-Team-SUPPLY : doit correspondre (release réelle)'),
    ('FR-Team-SUPPLY', 'Thunderbolts.2025.MULTI.VF2.2160p.WEB.DV.HDR.EAC3.5.1.H265-SUPPLY', 'movie', 1, 'Test parser — FR-Team-SUPPLY : doit correspondre (release réelle)'),
    ('FR-Team-Slay3R', 'Caught.Stealing.2025.MULTI.VF2.2160p.WEB.DV.HDR10Plus.AC3.5.1.H265-Slay3R', 'movie', 1, 'Capture Slay3R DV'),
    ('FR-Team-Slay3R', 'F1.Le.Film.2025.MULTITRUEFRENCH.2160p.WEB.EAC3.5.1.x265-Slay3R', 'movie', 1, 'Test parser — FR-Team-Slay3R : doit correspondre — ROADMAP Slay3R'),
    ('FR-Team-TFA', 'Canari.Noir.2024.MULTI.VF2.2160p.WEB.HDR10Plus.EAC3.5.1.H265-TFA', 'movie', 1, 'Test parser — FR-Team-TFA : doit correspondre (release réelle)'),
    ('FR-Team-TFA', 'Film.2024.MULTI.VFF.1080p.WEB-DL.x264-QTZ', 'movie', 0, 'Test parser — FR-Team-TFA : ne doit pas correspondre (release réelle)'),
    ('FR-Team-TFA', 'Karate.Kid.Legends.2025.MULTI.VFF.2160p.WEB.DV.HDR10.EAC3.5.1.x265-TFA', 'movie', 1, 'Test parser — FR-Team-TFA : doit correspondre (release réelle)'),
    ('FR-Team-THESYNDiCATE', 'Agent.Zeta.2026.MULTI.VFF.2160p.WEB.EAC3.5.1.H265-FW', 'movie', 0, 'Test parser — FR-Team-THESYNDiCATE : ne doit pas correspondre (release réelle)'),
    ('FR-Team-THESYNDiCATE', 'Destins.croises.2026.MULTI.VFF.2160p.WEB.DV.HDR.EAC3.5.1.H265-THESYNDiCATE', 'movie', 1, 'Test parser — FR-Team-THESYNDiCATE : doit correspondre (release réelle)'),
    ('FR-Team-THESYNDiCATE', 'Destins.croises.2026.MULTI.VFF.2160p.WEBRiP.DV.HDR.EAC3.5.1.AV1-THESYNDiCATE', 'movie', 1, 'Test parser — FR-Team-THESYNDiCATE : doit correspondre (release réelle)'),
    ('FR-Team-TyHD', 'La.Momie.1999.MULTI.VFF.2160p.WEB.DV.HDR10PLUS.AC3.5.1.H265-TyHD', 'movie', 1, 'Capture — Momie TyHD 2160p'),
    ('FR-Team-TyHD', 'Nightmare.Island.2020.MULTI.VFQ.2160p.WEB.SDR.AC3.5.1.H265-TyHD', 'movie', 1, 'TyHD WEB 2160p VFQ'),
    ('FR-Team-TOXIC', 'Aladdin.2019.MULTI.VFF.1080p.BluRay.HDLight.AC3.5.1.x264-TOXIC', 'movie', 1, 'Test parser — FR-Team-TOXIC : doit correspondre (release réelle)'),
    ('FR-Team-TOXIC', 'Joker.2019.MULTI.VFQ.1080p.BluRay.HDLight.AC3.5.1.x264-TOXIC', 'movie', 1, 'Test parser — FR-Team-TOXIC : doit correspondre (release réelle)'),
    ('FR-Team-TOXIC', 'Lords.Of.Chaos.2018.VOSTFR.1080p.HDLight.AC3.5.1.x264-TOXIC', 'movie', 1, 'Test parser — FR-Team-TOXIC : doit correspondre (release réelle)'),
    ('FR-Team-TOXIC', 'Shang.chi.et.la.legende.des.dix.anneaux.2021.MULTI.VF2.2160p.WEB.HDR10.EAC3.5.1.H265-ENIGMA', 'movie', 0, 'Test parser — FR-Team-TOXIC : ne doit pas correspondre (release réelle)'),
    ('FR-Team-TOXIC', 'The.Report.2019.MULTI.VFF.1080p.WEBRip.EAC3.5.1.x264-TOXIC', 'movie', 1, 'Test parser — FR-Team-TOXIC : doit correspondre (release réelle)'),
    ('FR-Tier-01', 'Agent.Zeta.2026.MULTI.VFF.2160p.WEB.DV.EAC3.5.1.H265-BOUC', 'movie', 0, 'Test parser — FR-Tier-01 : ne doit pas correspondre (release réelle)'),
    ('FR-Tier-01', 'Film.2016.MULTI.VFF.WEB-DL.1080p.h264-NEOSTARK', 'movie', 1, 'Test parser — FR-Tier-01 : doit correspondre (release réelle)'),
    ('FR-Tier-01', 'Film.2024.MULTI.VFF.1080p.WEB-DL.x264-BOUBA', 'movie', 1, 'Test parser — FR-Tier-01 : doit correspondre (release réelle)'),
    ('FR-Tier-02', 'Film.2016.MULTI.VFF.WEB-DL.1080p.h264-ENIGMA', 'movie', 0, 'Test parser — FR-Tier-02 : ne doit pas correspondre (release réelle)'),
    ('FR-Tier-02', 'Film.2024.MULTI.VFF.WEB-DL.1080p.x264-TLC', 'movie', 1, 'Test parser — FR-Tier-02 : doit correspondre (release réelle)'),
    ('FR-VF2', 'Film.2018.MULTI.VFF.Bluray.1080p.DTS.5.1.x264-AMEN', 'movie', 0, 'Test parser — FR-VF2 : ne doit pas correspondre (release réelle)'),
    ('FR-VF2', 'Film.2021.MULTI.VF2.UHD.2160p.DoVi.HDR10Plus.x265-TFA', 'movie', 1, 'Test parser — FR-VF2 : doit correspondre (release réelle)'),
    ('FR-VF2', 'Film.2022.MULTI.VOQ.2160p.BluRay.x265-QTZ', 'movie', 1, 'Test parser — FR-VF2 : doit correspondre (release réelle)'),
    ('FR-VF2', 'Film.2024.MULTi.VF2.WEB-DL.1080p.h264-TFA', 'movie', 1, 'Test parser — FR-VF2 : doit correspondre (release réelle)'),
    ('FR-VF2', 'Film.2024.VOSTFR.WEB-DL.1080p.x264-TEAM', 'movie', 0, 'Test parser — FR-VF2 : ne doit pas correspondre (release réelle)'),
    ('FR-VF2', 'Incendies.2010.VOQ.2160p.BluRay.DDP.x265-QTZ', 'movie', 1, 'Test parser — FR-VF2 : doit correspondre (release réelle)'),
    ('FR-VF2', 'Serie.S03E10.VFQ.WEB.1080p.EAC3.5.1.h264-FW', 'series', 1, 'Test parser — FR-VF2 : doit correspondre (release réelle)'),
    ('FR-VFF', 'F1.Le.Film.2025.MULTITRUEFRENCH.2160p.WEB.EAC3.5.1.x265-Slay3R', 'movie', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VFF', 'Film.2020.VFQ.WEB-DL.1080p.h264-AMEN', 'movie', 0, 'Test parser — FR-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-VFF', 'Film.2022.MULTI.VFI.WEB-DL.1080p.h264-TEAM', 'movie', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VFF', 'Film.2023.MULTI.VFF.Bluray.1080p.DTS-HD.MA.5.1.x264-TFA', 'movie', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VFF', 'Film.2024.FRENCH.SUBS.1080p.WEB-DL.x264-TEAM', 'movie', 0, 'Test parser — FR-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-VFF', 'Film.2024.VOSTFR.WEB-DL.1080p.x264-TEAM', 'movie', 0, 'Test parser — FR-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-VFF', 'Incendies.2010.VOQ.2160p.BluRay.DDP.x265-QTZ', 'movie', 0, 'Test parser — FR-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-VFF', 'Person.Of.Interest.S01.MULTI.FRENCH.1080p.WEBRip.x265-DELIRIUS', 'series', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VFF', 'Sept.Ecossais.Du.Texas.1966.MULTI.VF.1080p.WEBRip.AC3.2.0.x264-NOTAG', 'movie', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VFF', 'Serie.S01E04.TRUEFRENCH.WEB.720p.x264-FW', 'series', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VFF', 'Serie.S03E10.VF2.WEB.1080p.EAC3.5.1.h264-FW', 'series', 0, 'Test parser — FR-VFF : ne doit pas correspondre (release réelle)'),
    ('FR-VFF', 'The.Bear.S04.MULTI.VOF.1080p.WEB.EAC3.5.1.H264-TFA', 'series', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VFF', 'Top.Gun.1986.MULTI.VFI.2160p.BluRay.DolbyVision.Atmos.5.1.x265-QTZ', 'movie', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VFF', 'Twisters.2024.VFB.2160p.WEB.HDR.EAC3.5.1.H265-FW', 'movie', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VFF', 'Uncharted.2022.MULTI.VFF.2160p.BluRay.DV.EAC3.7.1.x265-QTZ', 'movie', 1, 'Test parser — FR-VFF : doit correspondre (release réelle)'),
    ('FR-VOSTFR', 'Anime.S01E01.FANSUB.1080p.WEB.h264-GROUP', 'series', 1, 'Test parser — FR-VOSTFR : doit correspondre (release réelle)'),
    ('FR-VOSTFR', 'Film.2024.MULTI.VF2.1080p.WEB-DL.h264-TEAM', 'movie', 0, 'Test parser — FR-VOSTFR : ne doit pas correspondre (release réelle)'),
    ('FR-VOSTFR', 'Film.2024.MULTI.VFF.UHD.2160p.x265-QTZ', 'movie', 0, 'Test parser — FR-VOSTFR : ne doit pas correspondre (release réelle)'),
    ('FR-VOSTFR', 'Film.US.2023.VOSTFR.WEB-DL.1080p.EAC3.5.1.h264-BOUBA', 'movie', 1, 'Test parser — FR-VOSTFR : doit correspondre (release réelle)'),
    ('FR-VOSTFR', 'MiniSerie.S01.SUBFRENCH.BluRay.720p.DD5.1.x264-TLC', 'series', 1, 'Test parser — FR-VOSTFR : doit correspondre (release réelle)'),
    ('FR-VOSTFR', 'Sentenced.To.Be.A.Hero.S01E01.VOSTFR.FASTSUB.1080p.WEBRip.AAC.2.0.x264-NOTAG', 'series', 1, 'Test parser — FR-VOSTFR : doit correspondre (release réelle)'),
    ('FR-VOSTFR', 'Serie.S02E03.VOST-FR.WEB.1080p.x264-TEAM', 'series', 1, 'Test parser — FR-VOSTFR : doit correspondre (release réelle)'),
    ('Full Disc', 'Aqua Teen Hunger Force (2000) S00E13 (480p DVD x265 SDR AAC 2.0 English - r00t QxR)', 'series', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'Bleach.S14.NTSC.DVD.LPCM2.0-NOGRP', 'series', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'Dan Da Dan AKA Dandadan S01E10 1080p CR WEB-DL AAC 2.0 x264-SubsPlease', 'series', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'El.Aviso.2018.SPANiSH.COMPLETE.BLURAY-CEBCOM', 'movie', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'Heaven''s Prisoners 1996 1080p AUS Blu-ray AVC LPCM 2.0-CultFilms™', 'movie', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'Hors-saison.2024.VOF.1080p.FRA.BluRay.AVC.DTS-HD.MA.5.1-RyanHG', 'movie', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'Life of Pi 2012 1080p BluRay x264-SPARKS', 'movie', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'Movie.2024.1080p.BluRay.REMUX.AVC.DTS-HD-GROUP', 'movie', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'Movie.2024.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — Full Disc : ne doit pas correspondre (release réelle)'),
    ('Full Disc', 'Planet Earth II S01 REPACK UHD BluRay 2160p DD5.1 HDR x265-BHDStudio', 'series', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'Scissor.Penis.2018.1080i.Blu-ray.AVC.DTS-HD.MA.2.0', 'movie', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'Spider-Man Across the Spider-Verse 2023 1080p UHD BluRay DDP7 1 DoVi HDR10x265-c0kE', 'movie', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', 'The Prisoner 2009 S01 1080i Blu-ray AVC DTS-HD MA 5.1-CultFilms™', 'series', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('Full Disc', '_Summer S00 JAPANESE 480p DVDRip DD 2.0 x264-Tsundere', 'series', 1, 'Test parser — Full Disc : doit correspondre (release réelle)'),
    ('HDR', 'Barbie (2023) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR TrueHD Atmos 7.1 English-FraMeSToR', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'Barbie (2023) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR TrueHD Atmos 7.1 English-FraMeSToR', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'Film.2024.2160p.BluRay.HDR10.x265-GROUP', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'Film.2024.2160p.BluRay.HLG.HDR.x265-GROUP', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'Film.2024.2160p.BluRay.PQ10.HDR.x265-GROUP', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'For a Few Dollars More aka Per qualche dollaro in più 1965 UHD BluRay 2160p DTS-HD MA 5.1 SDR HEVC REMUX-FraMeSToR', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'Game of Thrones (2011) S06 2160p UHD BluRay REMUX HEVC DV HDR TrueHD Atmos 7.1 English-FraMeSToR', 'series', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'Game of Thrones (2011) S06 2160p UHD BluRay REMUX HEVC DV HDR TrueHD Atmos 7.1 English-FraMeSToR', 'series', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'HDR', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'HDR+', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'HDR+', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'HDR10', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'HDR10', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'HDR10+', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'HDR10+', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'HDR10P', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'HDR10Plus', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'HLG HDR', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'Killers of the Flower Moon (2023) {tmdb-466420} [iT][WEBDL-2160p][DV HDR10Plus][EAC3 Atmos 5.1][h265]-FLUX.mkv', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'La Maison S01 REPACK 2160p ATVP WEB-DL Dual-Audio DD+ 5.1 Atmos DV HDR10+ H.265-Kitsune', 'series', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'Liu lang di qiu 2 AKA The Wandering Earth II 2023 2160p CHN UHD Blu-ray DoVi HDR10 HEVC TrueHD 7.1 Atmos-ANKO', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'Liu lang di qiu 2 AKA The Wandering Earth II 2023 2160p CHN UHD Blu-ray DoVi HDR10 HEVC TrueHD 7.1 Atmos-ANKO', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'PQ HDR', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'SDR HDR', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10 Plus TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10+ TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10+ TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10P TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 0, 'Test parser — HDR : ne doit pas correspondre (release réelle)'),
    ('HDR', 'Yojimbo.1961.REPACK.2160p.UHD.Blu-ray.Remux.SDR.HEVC.FLAC.1.0-CiNEPHiLES.mkv', 'movie', 1, 'Test parser — HDR : doit correspondre (release réelle)'),
    ('HDR10', 'Barbie (2023) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR TrueHD Atmos 7.1 English-FraMeSToR', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'Film.2024.2160p.BluRay.HDR10.x265-GROUP', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'Film.2024.2160p.BluRay.HLG.HDR.x265-GROUP', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'Film.2024.2160p.BluRay.PQ10.HDR.x265-GROUP', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'For a Few Dollars More aka Per qualche dollaro in più 1965 UHD BluRay 2160p DTS-HD MA 5.1 SDR HEVC REMUX-FraMeSToR', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'Game of Thrones (2011) S06 2160p UHD BluRay REMUX HEVC DV HDR TrueHD Atmos 7.1 English-FraMeSToR', 'series', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'HDR', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'HDR+', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'HDR10', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'HDR10', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'HDR10+', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'HDR10+', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'HDR10P', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'HDR10Plus', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'HLG HDR', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'Killers of the Flower Moon (2023) {tmdb-466420} [iT][WEBDL-2160p][DV HDR10Plus][EAC3 Atmos 5.1][h265]-FLUX.mkv', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'La Maison S01 REPACK 2160p ATVP WEB-DL Dual-Audio DD+ 5.1 Atmos DV HDR10+ H.265-Kitsune', 'series', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'La.Momie.1999.MULTI.VFF.2160p.WEB.DV.HDR10PLUS.AC3.5.1.H265-Slay3R', 'movie', 0, 'Momie — HDR10+ ne matche pas HDR10 seul'),
    ('HDR10', 'Liu lang di qiu 2 AKA The Wandering Earth II 2023 2160p CHN UHD Blu-ray DoVi HDR10 HEVC TrueHD 7.1 Atmos-ANKO', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'Liu lang di qiu 2 AKA The Wandering Earth II 2023 2160p CHN UHD Blu-ray DoVi HDR10 HEVC TrueHD 7.1 Atmos-ANKO', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'PQ HDR', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'SDR HDR', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10 Plus TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10+ TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10+ TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10P TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 0, 'Test parser — HDR10 : ne doit pas correspondre (release réelle)'),
    ('HDR10', 'Yojimbo.1961.REPACK.2160p.UHD.Blu-ray.Remux.SDR.HEVC.FLAC.1.0-CiNEPHiLES.mkv', 'movie', 1, 'Test parser — HDR10 : doit correspondre (release réelle)'),
    ('HDR10+', 'Film.2024.2160p.BluRay.HDR10.x265-GROUP', 'movie', 0, 'Test parser — HDR10+ : ne doit pas correspondre (release réelle)'),
    ('HDR10+', 'Film.2024.2160p.BluRay.HLG.HDR.x265-GROUP', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'Film.2024.2160p.BluRay.PQ10.HDR.x265-GROUP', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'For a Few Dollars More aka Per qualche dollaro in più 1965 UHD BluRay 2160p DTS-HD MA 5.1 SDR HEVC REMUX-FraMeSToR', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'HDR', 'movie', 0, 'Test parser — HDR10+ : ne doit pas correspondre (release réelle)'),
    ('HDR10+', 'HDR+', 'movie', 0, 'Test parser — HDR10+ : ne doit pas correspondre (release réelle)'),
    ('HDR10+', 'HDR10', 'movie', 0, 'Test parser — HDR10+ : ne doit pas correspondre (release réelle)'),
    ('HDR10+', 'HDR10+', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'HDR10P', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'HDR10Plus', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'HLG HDR', 'movie', 0, 'Test parser — HDR10+ : ne doit pas correspondre (release réelle)'),
    ('HDR10+', 'Killers of the Flower Moon (2023) {tmdb-466420} [iT][WEBDL-2160p][DV HDR10Plus][EAC3 Atmos 5.1][h265]-FLUX.mkv', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'La Maison S01 REPACK 2160p ATVP WEB-DL Dual-Audio DD+ 5.1 Atmos DV HDR10+ H.265-Kitsune', 'series', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'La.Momie.1999.MULTI.VFF.2160p.WEB.DV.HDR10PLUS.AC3.5.1.H265-Slay3R', 'movie', 1, 'Momie HDR10PLUS'),
    ('HDR10+', 'Liu lang di qiu 2 AKA The Wandering Earth II 2023 2160p CHN UHD Blu-ray DoVi HDR10 HEVC TrueHD 7.1 Atmos-ANKO', 'movie', 0, 'Test parser — HDR10+ : ne doit pas correspondre (release réelle)'),
    ('HDR10+', 'PQ HDR', 'movie', 0, 'Test parser — HDR10+ : ne doit pas correspondre (release réelle)'),
    ('HDR10+', 'SDR HDR', 'movie', 0, 'Test parser — HDR10+ : ne doit pas correspondre (release réelle)'),
    ('HDR10+', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10 Plus TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'Schindler''s List (1993) 2160p UHD BluRay Hybrid REMUX HEVC DV HDR10+ TrueHD Atmos 7.1 English-WiLDCAT', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('HDR10+', 'Yojimbo.1961.REPACK.2160p.UHD.Blu-ray.Remux.SDR.HEVC.FLAC.1.0-CiNEPHiLES.mkv', 'movie', 1, 'Test parser — HDR10+ : doit correspondre (release réelle)'),
    ('IMAX', 'A.Writers.Odyssey.2021.1080p.IMAX.BluRay.REMUX.AVC.TrueHD.7.1.Atmos-BELGiAN.mkv', 'movie', 1, 'Test parser — IMAX : doit correspondre (release réelle)'),
    ('IMAX', 'Movie.2024.DSNP.WEB-DL.1080p.x264-GROUP', 'movie', 0, 'Test parser — IMAX : ne doit pas correspondre (release réelle)'),
    ('IMAX', 'Movie.2024.DSNP.WEB-DL.IMAX.1080p.x264-GROUP', 'movie', 1, 'Test parser — IMAX : doit correspondre (release réelle)'),
    ('IMAX', 'Thor Ragnarok 2017 IMAX Enhanced 1080p HFR WEB-DL HDR10 HEVC 10bit DDP 5 1-Robo29', 'movie', 1, 'Test parser — IMAX : doit correspondre (release réelle)'),
    ('IMAX', 'Transformers Age Of Extinction 2014 NON-IMAX BluRay 1080p DTS AC3 x264-MgB', 'movie', 0, 'Test parser — IMAX : ne doit pas correspondre (release réelle)'),
    ('PCM', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — PCM : doit correspondre (release réelle)'),
    ('PCM', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — PCM : ne doit pas correspondre (release réelle)'),
    ('PCM', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — PCM : doit correspondre (release réelle)'),
    ('PCM', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — PCM : ne doit pas correspondre (release réelle)'),
    ('PCM', 'Film.AC3.2.0.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — PCM : ne doit pas correspondre (release réelle)'),
    ('PCM', 'Film.AC3.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — PCM : ne doit pas correspondre (release réelle)'),
    ('PCM', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — PCM : doit correspondre (release réelle)'),
    ('PCM', 'Film.LPCM.2.0.1080p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — PCM : doit correspondre (release réelle)'),
    ('PCM', 'Movie.2024.1080p.BluRay.AAC5.1.x264-GROUP', 'movie', 1, 'Test parser — PCM : doit correspondre (release réelle)'),
    ('PCM', 'Movie.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — PCM : ne doit pas correspondre (release réelle)'),
    ('PCM', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — PCM : ne doit pas correspondre (release réelle)'),
    ('PCM', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — PCM : doit correspondre (release réelle)'),
    ('PCM', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — PCM : doit correspondre (release réelle)'),
    ('PCM', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — PCM : ne doit pas correspondre (release réelle)'),
    ('Remux', 'Movie.2024.1080p.BluRay.REMUX.AVC.DTS-HD-GROUP', 'movie', 1, 'Test parser — Remux : doit correspondre (release réelle)'),
    ('Remux', 'Movie.2024.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — Remux : ne doit pas correspondre (release réelle)'),
    ('TrueHD', 'Album.FLAC.24bit.LOSSLESS-GROUP', 'movie', 1, 'Test parser — TrueHD : doit correspondre (release réelle)'),
    ('TrueHD', 'Film.2024.1080p.BluRay.DDP5.1.x264-GROUP', 'movie', 0, 'Test parser — TrueHD : ne doit pas correspondre (release réelle)'),
    ('TrueHD', 'Film.2024.2160p.UHD.BluRay.TrueHD.7.1.Atmos.x265-GROUP', 'movie', 1, 'Test parser — TrueHD : doit correspondre (release réelle)'),
    ('TrueHD', 'Film.AAC.5.1.1080p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — TrueHD : ne doit pas correspondre (release réelle)'),
    ('TrueHD', 'Film.AC3.2.0.720p.BluRay.x264-GROUP', 'movie', 0, 'Test parser — TrueHD : ne doit pas correspondre (release réelle)'),
    ('TrueHD', 'Film.DTS.5.1.720p.BluRay.x264-GROUP', 'movie', 1, 'Test parser — TrueHD : doit correspondre (release réelle)'),
    ('TrueHD', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 0, 'Test parser — TrueHD : ne doit pas correspondre (release réelle)'),
    ('TrueHD', 'Un-Ex You 2025 1080p NF WEB-DL DD 5.1 H.264-FLUX', 'movie', 1, 'Test parser — TrueHD : doit correspondre (release réelle)'),
    ('TrueHD', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 1, 'Test parser — TrueHD : doit correspondre (release réelle)'),
    ('TrueHD', 'Un-Ex You 2025 1080p NF WEB-DL DD+ 5.1 H.264-FLUX', 'movie', 0, 'Test parser — TrueHD : ne doit pas correspondre (release réelle)'),
    ('h265', 'Aqua Teen Hunger Force (2000) S00E13 (480p DVD x265 SDR AAC 2.0 English - r00t QxR)', 'series', 0, 'Test parser — h265 : ne doit pas correspondre (release réelle)'),
    ('h265', 'Planet Earth II S01 REPACK UHD BluRay 2160p DD5.1 HDR x265-BHDStudio', 'series', 0, 'Test parser — h265 : ne doit pas correspondre (release réelle)'),
    ('h265', 'The Batman (2022) (1080p HMAX WEB-DL H265 SDR DDP Atmos 5.1 English - HONE)', 'movie', 1, 'Test parser — h265 : doit correspondre (release réelle)'),
    ('h265', 'The Batman (2022) 1080p AMZN WEB-DL H265 SDR DDP 5.1 English-DarQ', 'movie', 1, 'Test parser — h265 : doit correspondre (release réelle)'),
    ('x264 (2160p)', 'Dan Da Dan AKA Dandadan S01E10 1080p CR WEB-DL AAC 2.0 x264-SubsPlease', 'series', 1, 'Test parser — x264 (2160p) : doit correspondre (release réelle)'),
    ('x264 (2160p)', 'Life of Pi 2012 1080p BluRay x264-SPARKS', 'movie', 1, 'Test parser — x264 (2160p) : doit correspondre (release réelle)'),
    ('x264 (2160p)', '_Summer S00 JAPANESE 480p DVDRip DD 2.0 x264-Tsundere', 'series', 1, 'Test parser — x264 (2160p) : doit correspondre (release réelle)'),
    ('x265', 'Aqua Teen Hunger Force (2000) S00E13 (480p DVD x265 SDR AAC 2.0 English - r00t QxR)', 'series', 1, 'Test parser — x265 : doit correspondre (release réelle)'),
    ('x265', 'Planet Earth II S01 REPACK UHD BluRay 2160p DD5.1 HDR x265-BHDStudio', 'series', 1, 'Test parser — x265 : doit correspondre (release réelle)'),
    ('x265', 'Spider-Man Across the Spider-Verse 2023 1080p UHD BluRay DDP7 1 DoVi HDR10x265-c0kE', 'movie', 1, 'Test parser — x265 : doit correspondre (release réelle)')
